# -*- coding: utf-8 -*-
"""Emit research/awakening/HANDOFF.md (internal drift/recovery log). Never let
this content leak into the paper."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
H = r"""# Awakening census retrofit (R1) -- internal handoff / drift log

Internal methods log for the provenance-retrofit of the awakening census
(queue item R1). Keep this OUT of the paper (FINDINGS-v2.md). The paper is the
clean record; this is how the sausage was made.

## What landed

- `research/awakening/build_dataset.py` -- the data-bound builder. Reads the
  frozen census, codes chronological stratum + attribution per mula event
  (rule functions over id + work_slug), computes every aggregate in code,
  writes a `v2` block + per-event `v2_*` keys back into
  `public/research/awakening-events.json`, and gates on a consistency check
  (counts, em-dash, recall non-decreasing, regression role-split exact).
  Prints `CONSISTENCY: PASS`.
- `research/awakening/_mula_workslug.json` -- the only DB-derived input
  (299 ids -> work_slug), captured serially from dhamma-pg. The stratum and
  attribution codes are pure functions of the work, so the builder is
  reproducible from this manifest without a live DB.
- `research/awakening/_sql_facts.json` -- the recall ladder, the marker-by-role
  counts, the quotative scan, the cross-recension link counts, and the
  regression role-split. Each value is a GROUP BY / count, not a search
  impression.
- `research/awakening/FINDINGS-v2.md` -- the paper (generated by `_gen_paper.py`).
- `research/awakening/_census_frozen_backup.json` -- the pre-retrofit census,
  so a re-run is recoverable.

## The triage decision (PASS A + PASS B)

Question type = typology, category (the members are asserted events with a who/
when/voice). The framework's typology-category row makes recall + chronology +
attribution load-bearing, and adds epistemic as optional. PASS B on the
enumerated claims: epistemic was NOT promoted -- the census records whether an
awakening is narrated, not whether it is staked under a verification formula,
so the load is on WHEN (stratum) and BY WHOSE VOICE (attribution). Cross-
recension stayed link-level corroboration only (the Apadana's lateness is
philological, not a parallel-table fact). Exclusions justified in the paper's
Methods + the v2 triage block.

## Drift points / recovery

1. **Niggahita-glyph recall cliff.** The naive surface string
   `arahattaṁ pāpuṇi` (bar-m, U+1E41) returns 2 rows; the corpus writes the
   niggahita as dotted-m (ṃ, U+1E43), giving 914 for the same family. This is
   the awakening analogue of the Uttarakuru long-u miss. It is reported as a
   Methods finding (the recall ladder rung-1 cliff), NOT as a recall correction
   to the census: the original census was already built at dotted-m depth (its
   299 mula events and evidence strings carry ṃ), so the 2,214 count did not
   move. Regression gate held; warrant logged here and in the paper.

2. **Apadana dual-attestation.** Apadana awakenings appear under BOTH the
   SuttaCentral id form (`tha-ap25`, 95 + `thi-ap`, 8) and the CST sibling form
   (`cst-s0510...`, 59) -- 162 total. Both are real distinct corpus rows (the
   same content, two ingest rows), exactly like the Uttarakuru SC/CST dups.
   They are both genuine census events; the 162 is correct, not a double-count
   error.

3. **Theragatha/Therigatha stratum.** Coded `archaic-or-late-canonical`,
   contested-confidence, NOT secure-early. The gathas carry archaic verse, but
   the awakening-NARRATION in these rows sits in the redactor-compiled
   biographical frame attached to the verse. Coding them early would have been
   the anti-pattern (reading a register/genre cue as a date). Flagged
   register-relative so a reviewer can challenge it. The finding survives either
   reading because the Apadana alone keeps the late bulk decisively larger than
   the early floor.

4. **Attribution honest default.** None of the 299 mula events is buddha-vacana.
   The honest default for a flat narrated awakening with no quotative owner is
   redactor-frame, not buddha-vacana (framework I.2). Confirmed by the quotative
   scan: 206 first-person, 22 bhagava etadavoca, 48 nidana-frame; the 22
   etadavoca rows carry the frame for the TEACHING, not for an assertion of the
   awakening. Coded buddha-vacana = 0.

## Serial DB discipline

All SQL ran one query at a time through `research/naga/sql.py` over the
flyctl proxy (15432:5432, dhamma-pg), password fetched live, never committed.
No fan-out. The box did not wedge.

## Spot-check anchors (for the coordinator)

- `cst-s0510m1.mul-kn10_1` -> work_role=mula, title "Buddhaapadanam" = Apadana,
  re-coded late-canonical.
- `cst-s0511m.mul-kn12_3` -> work_role=mula, Dipankara-Buddha verse =
  Buddhavamsa, re-coded late-canonical.
- a `pli-vism` event (e.g. `cst-e0102n.mul-4_p042`) -> work_role=mula but
  Visuddhimagga = classical-commentary; layer/stratum disagree.

## Prediction score (verbatim)

R1: "the commentarial/Apadana/Jataka awakening events are a *late* stratum
(chronology), not merely a separate voice; and that some are redactor-narrated,
not Buddha-vacana. PASS if >=1 large event-class re-codes late-canonical."
=> PASS. The Apadana (162, the largest mula class) re-codes late-canonical;
the Theragatha/Therigatha (59) also re-codes late; 261/299 mula rows carry a
layer/stratum disagreement; 0/299 are buddha-vacana (299 non-buddha-vacana).

## Verdict

CONFIRMED and SHARPENED (not changed). The original headline -- awakenings live
mostly in the commentaries, not the canon -- holds; the retrofit deepens it: the
'canon' share is itself mostly a late-canonical, hagiographic-narrated stratum,
and the canonical awakening corpus is narrated about the awakened, never staked
by the Buddha as his own asserted word.
"""
open(os.path.join(HERE, "HANDOFF.md"), "w", encoding="utf-8").write(H)
print("wrote HANDOFF.md", len(H), "chars; em-dashes:", H.count("—"))
